name: speack_cashless_mobility
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: any
  shared_preferences: any
  form_field_validator: any
  http: any 
  progress_indicators: any
  url_launcher: any

  # connectivity_plus:
  # image_picker: 
  # path_provider: 
  # device_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data.json
