name: speack_cashless_mobility
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: any
  shared_preferences: any
  form_field_validator: any
  http: any 
  progress_indicators: any
  url_launcher: any

  image_picker: 
  path_provider: 
  device_info: 
  # connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
